export const SIGNUP_ACTION = "SIGNUP_USER";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_START_LOADING = "SIGNUP_START_LOADING";
export const SIGNUP_STOP_LOADING = "SIGNUP_STOP_LOADING";
export const LOGIN_ACTION = "LOGIN_ACTION";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_START_LOADING = "LOGIN_START_LOADING";
export const LOGIN_STOP_LOADING = "LOGIN_STOP_LOADING";
