export const SIGNUP_ACTION = "SIGNUP_USER";
export const SIGNUP_ERROR = "SIGNUP_ERROR";
export const SIGNUP_START_LOADING = "SIGNUP_START_LOADING";
export const SIGNUP_STOP_LOADING = "SIGNUP_STOP_LOADING";
